# Generated by Django 5.0.6 on 2024-11-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/img')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('full_text', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(default='0р', max_length=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
