# Generated by Django 5.0.5 on 2024-11-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_text',
            field=models.TextField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.FloatField(max_length=50, verbose_name='Наименование'),
        ),
    ]
